# Generated by Django 4.2.3 on 2023-07-29 00:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="name",
            new_name="nickname",
        ),
    ]
