# Generated by Django 4.2.3 on 2023-08-04 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0001_initial"),
        ("users", "0004_user_thumbnail_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="MEP",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="MEP_voters",
                to="competition.player",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="MVP",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="MVP_voters",
                to="competition.player",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="cheer_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="competition1_POG",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="competition1_POG_voters",
                to="competition.player",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="competition1_winner_expect",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="competition1_expectors",
                to="competition.team",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="competition2_POG",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="competition2_POG_voters",
                to="competition.player",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="competition2_winner_expect",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="competition2_expectors",
                to="competition.team",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="competition3_POG",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="competition3_POG_voters",
                to="competition.player",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="competition3_winner_expect",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="competition3_expectors",
                to="competition.team",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="info_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="support_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supporters",
                to="competition.team",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="twitch_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
