# Generated by Django 4.2.3 on 2023-08-12 10:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_user_mep_user_mvp_user_cheer_message_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="MEP",
        ),
        migrations.RemoveField(
            model_name="user",
            name="MVP",
        ),
        migrations.RemoveField(
            model_name="user",
            name="cheer_message",
        ),
        migrations.RemoveField(
            model_name="user",
            name="competition1_POG",
        ),
        migrations.RemoveField(
            model_name="user",
            name="competition1_winner_expect",
        ),
        migrations.RemoveField(
            model_name="user",
            name="competition2_POG",
        ),
        migrations.RemoveField(
            model_name="user",
            name="competition2_winner_expect",
        ),
        migrations.RemoveField(
            model_name="user",
            name="competition3_POG",
        ),
        migrations.RemoveField(
            model_name="user",
            name="competition3_winner_expect",
        ),
        migrations.RemoveField(
            model_name="user",
            name="info_complete",
        ),
        migrations.RemoveField(
            model_name="user",
            name="support_team",
        ),
        migrations.RemoveField(
            model_name="user",
            name="twitch_id",
        ),
    ]
