# Generated by Django 4.2.3 on 2023-08-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_remove_user_mep_remove_user_mvp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="chat_name_color",
            field=models.CharField(
                choices=[
                    ("#FF0000", "빨강"),
                    ("#FCEE21", "노랑"),
                    ("#39B54A", "초록"),
                    ("#29ABE2", "파랑"),
                    ("#000000", "검정"),
                ],
                default="#000000",
                max_length=10,
            ),
        ),
    ]
