# Generated by Django 4.2.3 on 2023-08-15 00:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_user_join_quiz"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="solved_point",
            field=models.IntegerField(default=0),
        ),
    ]
