# Generated by Django 4.2.3 on 2023-07-29 09:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("smalltalk", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="smalltalk",
            options={"ordering": ["created"]},
        ),
    ]
