# Generated by Django 4.2.3 on 2023-08-04 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=30)),
                ("nickname", models.CharField(max_length=100)),
                (
                    "position",
                    models.CharField(
                        choices=[("bottom", "원딜"), ("jungle", "정글"), ("mid", "미드"), ("top", "탑"), ("supporter", "서폿")],
                        max_length=30,
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("bronze", "브론즈"),
                            ("silver", "실버"),
                            ("gold", "골드"),
                            ("platinum", "플래티넘"),
                            ("emerald", "에메랄드"),
                            ("diamond", "다이아"),
                            ("master", "마스터"),
                            ("grand_master", "그마"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="players", to="competition.team"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Competition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number", models.IntegerField(default=0)),
                ("open_POG_vote", models.BooleanField(default=False)),
                ("finish_POG_vote", models.BooleanField(default=False)),
                ("open_expect_vote", models.BooleanField(default=False)),
                ("finish_expect_vote", models.BooleanField(default=False)),
                (
                    "team1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team1",
                        to="competition.team",
                    ),
                ),
                (
                    "team2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team2",
                        to="competition.team",
                    ),
                ),
            ],
        ),
    ]
