# Generated by Django 4.2.3 on 2023-08-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="competition",
            options={"ordering": ["number"]},
        ),
        migrations.AddField(
            model_name="team",
            name="number",
            field=models.IntegerField(default=1),
        ),
    ]
