# Generated by Django 4.2.3 on 2023-08-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0002_alter_competition_options_team_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("twitch", models.BooleanField(default=False)),
                ("youtube", models.BooleanField(default=True)),
            ],
        ),
    ]
