# Generated by Django 4.2.3 on 2023-08-12 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0006_remove_user_mep_remove_user_mvp_and_more"),
        ("competition", "0003_setting"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="player",
            options={"ordering": ["created"]},
        ),
        migrations.RemoveField(
            model_name="competition",
            name="finish_POG_vote",
        ),
        migrations.RemoveField(
            model_name="competition",
            name="finish_expect_vote",
        ),
        migrations.RemoveField(
            model_name="competition",
            name="open_POG_vote",
        ),
        migrations.RemoveField(
            model_name="competition",
            name="open_expect_vote",
        ),
        migrations.RemoveField(
            model_name="competition",
            name="team1",
        ),
        migrations.RemoveField(
            model_name="competition",
            name="team2",
        ),
        migrations.RemoveField(
            model_name="player",
            name="name",
        ),
        migrations.RemoveField(
            model_name="player",
            name="nickname",
        ),
        migrations.RemoveField(
            model_name="player",
            name="position",
        ),
        migrations.RemoveField(
            model_name="player",
            name="team",
        ),
        migrations.RemoveField(
            model_name="player",
            name="tier",
        ),
        migrations.AddField(
            model_name="competition",
            name="description",
            field=models.TextField(default="설명이 필요합니다.", verbose_name="설명"),
        ),
        migrations.AddField(
            model_name="competition",
            name="game_link",
            field=models.URLField(blank=True, null=True, verbose_name="게임 링크"),
        ),
        migrations.AddField(
            model_name="competition",
            name="joinable",
            field=models.BooleanField(default=False, verbose_name="참가 가능"),
        ),
        migrations.AddField(
            model_name="competition",
            name="name",
            field=models.CharField(default="경기명 설정이 필요합니다.", max_length=200, verbose_name="경기명"),
        ),
        migrations.AddField(
            model_name="competition",
            name="real_time",
            field=models.BooleanField(default=False, verbose_name="실시간"),
        ),
        migrations.AddField(
            model_name="competition",
            name="youtube_link",
            field=models.URLField(blank=True, null=True, verbose_name="유튜브 링크"),
        ),
        migrations.AddField(
            model_name="player",
            name="competition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="players",
                to="competition.competition",
                verbose_name="경기",
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="players",
                to=settings.AUTH_USER_MODEL,
                verbose_name="유저",
            ),
        ),
        migrations.DeleteModel(
            name="Team",
        ),
    ]
