# Generated by Django 4.2.3 on 2023-08-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0004_alter_player_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="time_string",
            field=models.CharField(default="시간 설정이 필요합니다.", max_length=30),
        ),
    ]
