# Generated by Django 4.2.3 on 2023-08-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0006_setting_broad_cast_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="competition",
            name="youtube_link",
        ),
        migrations.AddField(
            model_name="competition",
            name="discord_link",
            field=models.URLField(blank=True, null=True, verbose_name="디스코드 링크"),
        ),
    ]
