# Generated by Django 4.2.3 on 2023-08-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0007_remove_competition_youtube_link_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="competition",
            options={"ordering": ["-number"]},
        ),
        migrations.AlterField(
            model_name="competition",
            name="joinable",
            field=models.BooleanField(default=True, verbose_name="참가 가능"),
        ),
    ]
