# Generated by Django 4.2.3 on 2023-08-13 00:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0010_alter_player_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="competition",
            options={"ordering": ["number"]},
        ),
    ]
