# Generated by Django 4.2.3 on 2023-08-14 23:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0012_player_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="setting",
            name="iframe_tag",
            field=models.TextField(default="설정필요"),
        ),
    ]
