# Generated by Django 4.2.3 on 2023-08-14 23:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("genre", models.CharField(max_length=100)),
                ("point", models.IntegerField(choices=[(30, 30), (40, 40), (50, 50)])),
                ("solved", models.BooleanField(default=False)),
                ("answer", models.TextField()),
            ],
        ),
    ]
