# Generated by Django 4.2.3 on 2023-08-15 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0002_quiz_solver"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="answer_image",
            field=models.ImageField(blank=True, null=True, upload_to="quizs"),
        ),
        migrations.AddField(
            model_name="quiz",
            name="description_image",
            field=models.ImageField(blank=True, null=True, upload_to="quizs"),
        ),
    ]
