# Generated by Django 4.2.3 on 2023-08-15 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quiz", "0003_quiz_answer_image_quiz_description_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="solver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="solved_quizs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
